author: "Jeffrey Louden"
title: "Jeffrey Louden"
description: "Director of Technology at The New York Times. Formerly Google, The New Yorker, Obama for America, and Apple."
intro: "Director of Technology at The&nbsp;New&nbsp;York&nbsp;Times. Formerly Google, The&nbsp;New&nbsp;Yorker, Obama&nbsp;for&nbsp;America, and Apple."
twitter_handle: "@jeffreylouden"
